---
title: "Code of Conduct"
page-layout: full
---

# Overview

Southern California R Users Group (SoCal RUG) is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of participants in any form.

This Code of Conduct applies to all SoCal RUG spaces, including meetups, Twitter, Slack, mailing lists, both online and offline. Anyone who violates this Code of Conduct may be sanctioned or expelled from these spaces at the discretion of the organizers.

# Examples of Harassment

* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.
* Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
* Deliberate misgendering or use of ‘dead’ or rejected names.
* Gratuitous or off-topic sexual images or behaviour in spaces where they’re not appropriate.
* Physical contact and simulated physical contact (eg, textual descriptions like “hug” or “backrub“) without consent or after a request to stop.
* Threats of violence.
* Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
* Deliberate intimidation.
* Stalking or following.
* Harassing photography or recording, including logging online activity for harassment purposes.
* Sustained disruption of discussion.
* Unwelcome sexual attention.
* Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others.
* Continued one-on-one communication after requests to cease.
* Deliberate "outing" of any aspect of a person’s identity without their consent except as necessary to protect vulnerable people from intentional abuse.
* Publication of non-harassing private communication.

SoCal RUG prioritizes marginalized people’s safety over privileged people’s comfort. The organizers will not act on complaints regarding:

* ‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’.
* Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
* Communicating in a ‘tone’ you don’t find congenial.
* Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions.

# Reporting

If you are being harassed by a member/guest/participant of/at SoCal RUG, notice that someone else is being harassed, or have any other concerns, please contact the organizers via <a href="mailto:orangecounty.rug@gmail.com" target="_blank">orangecounty.rug@gmail.com</a>. Local incidences will be handled together with the local organisers. If the person who is harassing you is on the team, they will recuse themselves from handling your incident. We will respond as promptly as we can.

This Code of Conduct applies to SoCal RUG spaces, but if you are being harassed by a member/guest/participant of/at SoCal RUG outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by SoCal RUG members, especially the organizers, seriously. This includes harassment outside our spaces and harassment that took place at any point in time. The organizers reserve the right to exclude people from SoCal RUG based on their past behavior, including behavior outside SoCal RUG spaces and behavior towards people who are not in SoCal RUG.

In order to protect volunteers from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response.

We will respect confidentiality requests for the purpose of protecting victims of abuse. At our discretion, we may publicly name a person about whom we’ve received harassment complaints, or privately warn third parties about them, if we believe that doing so will increase the safety of SoCal RUG members or the general public. We will not name harassment victims without their affirmative consent.

# Consequences

Participants asked to stop any harassing behavior are expected to comply immediately.

If a participant engages in harassing behavior, the organizers may take any action they deem appropriate, up to and including expulsion from all SoCal RUG spaces and identification of the participant as a harasser to other SoCal RUG members or the general public.

This policy is licensed under the Creative Commons Zero license.

# Reference

This Code of Conduct also includes the [R Consortium and the R Community Code of Conduct](https://wiki.r-consortium.org/view/R_Consortium_and_the_R_Community_Code_of_Conduct).